### ISSUE TITLE
Problem with LLVM when importing Sionna

### ISSUE THREAD

**Issue by bchateli** [NVlabs/sionna#107]
Hi everyone,

First of all, thank you very much for this great tool.

I am having somme issues when importing Sionna 0.14.0 in both Windows 10 and Ubuntu 22.04. This throws an error regarding LLVM:

(Windows)
`AttributeError: jit_init_thread_state(): the LLVM backend is inactive because the LLVM shared library ("LLVM-C.dll") could not be found! Set the DRJIT_LIBLLVM_PATH environment variable to specify its path.`

(Ubuntu)
`jit_init_thread_state(): the LLVM backend is inactive because the LLVM shared library ("libLLVM.so") could not be found! Set the DRJIT_LIBLLVM_PATH environment variable to specify its path..`

On Ubuntu, adding LLVM with `sudo apt-get install llvm-13` solved the issue when executing Sionna RT in scripts, but I still get the same error when running the Jupyter Sionna RT tutorial notebook.

Do you have any idea how to solve it ?

Thanks in advance  !

**Comment by merlinND** [comment]
Hello @bchateli,

The following instructions should help on Windows: https://drjit.readthedocs.io/en/latest/firststeps-py.html#llvm-backend

On Ubuntu, you've already installed LLVM via `apt`, which is supposed to be all that's needed.
Was the Jupyter server that you use installed with Conda? If so you might need to install LLVM via Conda as well, since I believe that Conda may interfere with the library lookup. You could also try with a pip-installed Jupyter notebook server.

Following the error message, there is also always the option to explicitly set the `DRJIT_LIBLLVM_PATH` environment variable to point to the LLVM shared library before starting the Jupyter server:

```sh
export DRJIT_LIBLLVM_PATH='/path/to/llvm.so'
python3 -m jupyterlab .
```

**Comment by bchateli** [comment]
Hello @merlinND,

Everything works fine on Windows now, thank you very much.

Also thank you very much for your help on Ubuntu, I'll try it !
