### ISSUE TITLE
Sionna import error 

### ISSUE THREAD

**Issue by s311295** [NVlabs/sionna#168]
when i try to import sionna on google collab i run in to the following error 
---------------------------------------------------------------------------

```
AssertionError                            Traceback (most recent call last)

[<ipython-input-4-da63c5ec0d80>](https://localhost:8080/#) in <cell line: 7>()
      6 # Import Sionna
      7 try:
----> 8     import sionna as sn
      9 except ImportError as e:
     10     # Install Sionna if package is not already installed

18 frames

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/saved_model/revived_types.py](https://localhost:8080/#) in register_revived_type(identifier, predicate, versions)
    131           f"Got multiple registrations with version {registration.version} for "
    132           f"type {identifier}.")
--> 133     version_numbers.add(registration.version)
    134 
    135   if identifier in _REVIVED_TYPE_REGISTRY:

AssertionError: Duplicate registrations for type 'experimentalOptimizer'
```

**Comment by jhoydis** [comment]
Hi,

Thank you for reporting this bug. The issue is that Colab has switched to TF 2.12.0 which is currently excluded from Sionna's requirements to ensure CVE compliance. When you run `pip install sionna` in the notebook, it will upgrade TF to a newer version. The error you observe happens because TF has been imported prior to upgrading it. Simply restarting the kernel should solve the issue. We are currently working on a fix.

**Comment by s311295** [comment]
thank you so much it did solve the issue when i degrade TF to 2.12.0

**Comment by hussjazi** [comment]
is there a possibility to use the older version of Sionna in colab ?

**Comment by jhoydis** [comment]
Hi @hussjazi,

Yes, cou can. The notebooks for v0.19.2 can be found [here](https://jhoydis.github.io/sionna-0.19.2-doc/tutorials.html) and you can start them immediately on Colab.
