### ISSUE TITLE
The simulation results for 5G Polar+CRC OSD are different

### ISSUE THREAD

**Issue by baymax92** [NVlabs/sionna#182]
Hello, I found that in your 5G Polar Code example, the results with the 5G Polar+CRC OSD-4 you gave are not the same as in [1], and after looking at it for a long time I didn't find the reason for that. I tried to use the OSD-2 you gave and found that it actually performs the same as the OSD-3 in Fig. 4 in [1], can you explain? Thank you very much.
[1]D. Wu, Y. Li, X. Guo and Y. Sun, “Ordered Statistic Decoding for Short Polar Codes,” IEEE Commun. Lett., vol. 20, no. 6, pp. 1064-1067, Jun. 2016.
[Ordered_Statistic_Decoding_for_Short_Polar_Codes.pdf](https://github.com/NVlabs/sionna/files/12185803/Ordered_Statistic_Decoding_for_Short_Polar_Codes.pdf)

**Comment by SebastianCa** [comment]
Hi,

please note that the paper you provided uses a CRC of degree 8, while the Sionna example operates with a CRC of degree 11. As such, the resulting concatenated codes may perform differently under OSD. Also, the Polar code construction could differ.

A way to verify this would be to replicate the experiment using a custom Polar code construction and the same CRC polynomial as in [1].

**Comment by baymax92** [comment]
Hello, in fact, I have also tried simulation with CRC11 and CRC8, and the impact on OSD performance is not significant. Furthermore, I would like to ask whether OSD decoding is related to CRC. OSD itself only selects the result with the minimum Euclidean distance and does not perform CRC verification. 

I'm sorry, I have been trying to align the simulation results with yours, but I haven't been successful. I would greatly appreciate it if you could help me clarify my doubts. Thank you!

**Comment by SebastianCa** [comment]
Hi,

in the Sionna example, we simulate the performance of the concatenated code (CRC + Polar) by considering both encoders as a single entity (i.e., a new linear block code). The CRC - which is known for its strong minimum distance properties - helps to generate a code that exhibits strong performance under maximum likelihood decoding, which OSD essentially approximates.

In contrast, your reference seems to employ OSD to decode the Polar code solely and uses the CRC for the selection of valid candidates in a post-processing stage. This could explain the differences between the two setups.

In order to verify this theory, one would need to modify Sionna’s OSD decoder to return a list of the L most likely candidates and apply the CRC check in a separate step.

**Comment by baymax92** [comment]
Thank you very much. You‘re right. When I consider the CRC-polar code as a new linear code，the simulation results become similar with yours.
