### ISSUE TITLE
Suggestion: adding Matplotlib and Plotly plotting backends

### ISSUE THREAD

**Issue by jeertmans** [NVlabs/sionna#219]
Hello,

The current `scene.preview()` is great, but only works in Jupyter Notebooks.
In my opinion, plots are very important to test simulation models and also communicate results.
The restriction to notebooks, and the lack of plotting options, could both be solved by supporting more plotting backends.

If you are interested, I'd love to make a PR adding one or two plotting backends, mainly Matplotlib and Plotly, and also the possibility to easily switch between them using a syntax similar to what
[Pandas does](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html).

**Comment by merlinND** [comment]
Hello @jeertmans,

`scene.preview()` is designed to provide an interactive 3D view of the scene, optionally including radio devices and the simulated paths.
In case interactivity is not available (e.g. outside of Jupyter notebooks), there is the option to fallback on Mitsuba-based rendering of a single preview image.

Since `scene.preview()` is not actually plotting but rather rendering, what do you have in mind for Matplotlib and Plotly backends?

**Comment by jeertmans** [comment]
Hello @merlinND,

I have thinking to add a plot method to the Scene and Path classes. I have myself already implemented a few alternatives to the current rendering. 

The goal is to rerun an easy to modify and customize plot (with Artists for Matplotlib or Traces for Plotly). Since scenes are mostly lines (paths) and triangles, I think the implement and the plotting speed should be ok. And 3D manipulation is quite nice with both backends, with a variety of export formats. 

I don’t know about the coverage map though.

**Comment by jhoydis** [comment]
This should be moved to the discussions as it does not describe an issue.
