### ISSUE TITLE
Specifying Transmit Power and Coderate for each UT in a multi-user Scenario

### ISSUE THREAD

**Issue by abdallah1097** [NVlabs/sionna#316]
Hello All, first of all thank you so much for such a fascinating framework. Referring to this [tutorial](https://nvlabs.github.io/sionna/examples/Realistic_Multiuser_MIMO_Simulations.html?highlight=multi%20users), my questions are:

1. **How can I change transmit power of a user?**

I thought about changing the ebno:
`
ebno_db = 10
no = ebnodb2no(ebno_db, num_bits_per_symbol, coderate, rg)
`
but for a multi-user case which is in my case, this will change the Tx power for all users since later in the code, we use the no as this:
`y = channel_freq([x_rg, h_freq, no])`
This means all users will experience the same no, which means it is changed to all users the same, but I want to apply it per user.

Can you help me on how to set a transmitter power for the user's antennas?

2. **Also can I set a code rate for each user in the same example?**

**Comment by jhoydis** [comment]
Hi,

You could simply scale the dimensions of `x_rg` corresponding to different users by different values. That would give every user and individual transmit power.

You cannot simply set a different code rate for each user because you would require a different encoder/decoder for each code rate. However, nothing prevents you from constructing a tensor `x` by stacking the outputs of different encoders together. At the receiver, you would need to unstack the LLRs coming out of the demapper and feed the tensors into different decoders.  You can do the same approach for user-specific modulation schemes.

Hope that helps you to progress on your problem.

**Comment by abdallah1097** [comment]
Thank you @jhoydis. Do you care if I fork and implement either an example showing this case or even change the grid mapped to assign power per user?
