### ISSUE TITLE
Local installing

### ISSUE THREAD

**Issue by vanwayplus** [NVlabs/sionna#323]
Is it possible to install Sionna on an off-line machine? Due to some security policies, we can't use pip or conda for online downloading.

**Comment by jhoydis** [comment]
Hi,

I think that this issue is not Sionna-specific but would apply to any package on pypi.org. 

In principle, you could simply download or clone the repository to USB stick, transfer it to your off-line machine and then run make install. However, you would need to do the same process for all of the packages that are required by Sionna which might become tedious.

An alternative approach that I could imagine is to prepare a Docker container with everything installed that you would then simply save to disk (see https://docs.docker.com/engine/reference/commandline/image_save/) and transfer to your off-line machine (assuming that Docker is available).

Maybe there are options that would allow you to transfer a conda enviroment from one machine to another (e.g., https://stackoverflow.com/questions/31729731/how-can-i-install-a-conda-environment-when-offline), but I have no experience with this.

Hope that gives you some pointers.

**Comment by vanwayplus** [comment]
Thanks! That would be pretty helpful!
