### ISSUE TITLE
Dimension discrepancy for 'a' vs 'tau'/'theta_r' in compute_paths()

### ISSUE THREAD

**Issue by lllck** [NVlabs/sionna#547]
Hello! Could you please clarify why the dimension of '**a**' in the paths returned by **scene.compute_paths()** is [batch_size, num_rx, num_rx_ant, num_tx, num_tx_ant, max_num_paths, num_time_steps], while other parameters like '**tau**' and '**theta_r**' have dimensions of [batch_size, num_rx, num_tx, max_num_paths]? Why do these other parameters lack the antenna number dimensions?

**Comment by SebastianCa** [comment]
Hi @lllck, 
this happens if you run the ray tracer with `synthetic_array=True` which means ray tracing is done from the center of the antenna array. Thus, only one path length exists. If you set `synthetic_array=False` you will get individual paths for each antenna element and, thus, the additional dimensions for `tau`.

Closing this issue as the described behaviour is expected.
