### ISSUE TITLE
Error in resource grid 624 subcarriers and 8 streams

### ISSUE THREAD

**Issue by alejandroBlancoPizarro** [NVlabs/sionna#623]
Dear Sionna community,

I am trying to simulate a 5G link using 10MHz (624 subcarriers) and 8 streams.

However, I got an error when calling the ResourceGrid function. This error applies only to 8 streams, for 2 and 4 streams works fine. 

The Sionna version is 0.16.

Below is a screenshot of the error. I understand from the error that the size of the calculated pilots is not the same as the allocated positions of the pilots, but I am not sure how to handle it. 

![Screenshot from 2024-10-17 08-29-24](https://github.com/user-attachments/assets/347f7350-0cd1-454b-bded-7f13e520c9dd)

**Comment by alejandroBlancoPizarro** [comment]
Hello Jakob,

Ok, I will try your solution, it looks feasible to me. 

Thanks and best regards,
Alejandro

**Comment by SebastianCa** [comment]
Hi @alejandroBlancoPizarro,

The issue with your code is that `num_effective_subcarriers=612` is not a multiple of `num_streams=8`. Sionna should raise an assertion in such cases. This will be fixed in the next release of Sionna.

As a workaround, you can either remove the guard carriers (including DC nulling) or adjust the `fft_size` accordingly.

**Comment by alejandroBlancoPizarro** [comment]
Hello @SebastianCa,

Thanks for the clarification. I removed the guard carriers and the error is gone. 

We can close this issue.

Best,
Alejandro
